// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhnliHbm9jlkXPSOT2cNl7iE-861-RnXA',
    appId: '1:1046381169929:web:4b49fb69f3a75130ae17d8',
    messagingSenderId: '1046381169929',
    projectId: 'betroom24-7b368',
    authDomain: 'betroom24-7b368.firebaseapp.com',
    databaseURL: 'https://betroom24-7b368-default-rtdb.firebaseio.com',
    storageBucket: 'betroom24-7b368.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSSa1wgp6vx4zVVtTY5FW2u9QtNeW1oCc',
    appId: '1:1046381169929:android:c54062d92646cdf8ae17d8',
    messagingSenderId: '1046381169929',
    projectId: 'betroom24-7b368',
    databaseURL: 'https://betroom24-7b368-default-rtdb.firebaseio.com',
    storageBucket: 'betroom24-7b368.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDTlt6dZE5UvMXhcWSUGkjKmScVtSpzH4',
    appId: '1:1046381169929:ios:2868f3b347c8effaae17d8',
    messagingSenderId: '1046381169929',
    projectId: 'betroom24-7b368',
    databaseURL: 'https://betroom24-7b368-default-rtdb.firebaseio.com',
    storageBucket: 'betroom24-7b368.appspot.com',
    iosClientId: '1046381169929-8s0amr6d5ra2dd8dd2jv2kb8b501c8ag.apps.googleusercontent.com',
    iosBundleId: 'com.example.brb100x',
  );
}
